#!/usr/bin/env bash
# Builds the web app for GitHub Pages (https://<owner>.github.io/fly-app/).
#
# Two things the stock `flutter build web` does not do:
#   * CanvasKit is served from the page's own origin (--no-web-resources-cdn)
#     instead of gstatic, so nothing the app needs lives on another host.
#   * Flutter's own service worker is a stub that unregisters itself, and
#     its loader never registers one for the first time anyway. sw.js is
#     generated here, precaches the app and is registered from index.html,
#     so a page opened once with signal opens again at a launch site.
set -euo pipefail

cd "$(dirname "$0")/.."

flutter build web --release --base-href /fly-app/ --no-web-resources-cdn

cd build/web

# Everything the dart2js + CanvasKit build can load. The .symbols files are
# debug-only, and skwasm / wimp / webparagraph belong to the Wasm renderers.
precache=$(find . -type f \
    ! -name '*.symbols' \
    ! -name '.last_build_id' \
    ! -name 'flutter_service_worker.js' \
    ! -name 'sw.js' \
    ! -path './canvaskit/skwasm*' \
    ! -path './canvaskit/wimp*' \
    ! -path './canvaskit/webparagraph/*' \
  | sed 's#^\./##' | sort | sed 's/.*/  "&",/')

# Named after the content, not .last_build_id, which survives a rebuild with
# different output: cache-first would then serve the old app forever.
version=$(echo "$precache" | sed 's/^  "\(.*\)",$/\1/' | xargs cat | shasum | cut -c1-16)

cat > sw.js <<EOF
'use strict';

// Generated by tool/build_web.sh. Cache-first: the app is served from the
// cache when there is one, so it opens with no network at all.
const CACHE = 'fly-app-${version}';
const PRECACHE = [
  "./",
${precache}
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(request, { ignoreSearch: true });
    if (cached) return cached;
    const response = await fetch(request);
    if (response.ok) cache.put(request, response.clone());
    return response;
  })());
});
EOF

echo "Service worker precaches $(echo "$precache" | wc -l | tr -d ' ') files (cache ${version})."
